import gspread
import pandas as pd

from credentials.mongodb import students


def update_mzc_data():

    query = {
        "School Name": "Montezuma Creek Elementary"
    }

    cols = [
        # Demographics
        "Student Preferred Last Name", 
        "Student Preferred First Name", 
        "Grade Level", 
        "ELL",

        # Attendance Data
        "Term 1 Total Absences",
        "Term 1 Total Excused Absences",
        "Term 1 Total Unexcused Absences",
        "Term 1 Tardies",
        "Term 2 Total Absences",
        "Term 2 Total Excused Absences",
        "Term 2 Total Unexcused Absences",
        "Term 2 Tardies",
        "Term 3 Total Absences",
        "Term 3 Total Excused Absences",
        "Term 3 Total Unexcused Absences",
        "Term 3 Tardies",
        "YTD Total Absences",
        "YTD Total Excused Absences",
        "YTD Total Unexcused Absences",
        "YTD Tardies",

        # WIDA
        "WIDA Overall",
        "WIDA Reading",
        "WIDA Literacy",
        "WIDA Comprehension",
        "WIDA Writing",
        "WIDA Oral",
        "WIDA Speaking",
        "WIDA Listening",

        # This year's Acadience Reading
        'Reading Composite Score (BOY)',
        'Reading Composite Status (BOY)',
        'Lexile Reading (BOY)',
        'FSF Score (BOY)',
        'FSF Status (BOY)',
        'LNF Score (BOY)',
        'Maze Adjusted Score (BOY)',
        'Maze Status (BOY)',
        'NWF CLS Score (BOY)',
        'NWF CLS Status (BOY)',
        'NWF WWR Score (BOY)',
        'NWF WWR Status (BOY)',
        'ORF Accuracy Score (BOY)',
        'ORF Accuracy Status (BOY)',
        'ORF WC Score (BOY)',
        'ORF WC Status (BOY)',
        'PSF Score (BOY)',
        'PSF Status (BOY)',
        'Retell Quality Score (BOY)',
        'Retell Quality Status (BOY)',
        'Retell Score (BOY)',
        'Retell Status (BOY)',
        'Reading Composite Score (MOY)',
        'Reading Composite Status (MOY)',
        'Lexile Reading (MOY)',
        'FSF Score (MOY)',
        'FSF Status (MOY)',
        'LNF Score (MOY)',
        'Maze Adjusted Score (MOY)',
        'Maze Status (MOY)',
        'NWF CLS Score (MOY)',
        'NWF CLS Status (MOY)',
        'NWF WWR Score (MOY)',
        'NWF WWR Status (MOY)',
        'ORF Accuracy Score (MOY)',
        'ORF Accuracy Status (MOY)',
        'ORF WC Score (MOY)',
        'ORF WC Status (MOY)',
        'PSF Score (MOY)',
        'PSF Status (MOY)',
        'Retell Quality Score (MOY)',
        'Retell Quality Status (MOY)',
        'Retell Score (MOY)',
        'Retell Status (MOY)',

        # This year's Acadience Math
        'Math Composite Score (BOY)',
        'Math Composite Status (BOY)',
        'AQD Score (BOY)',
        'AQD Status (BOY)',
        'BQD Score (BOY)',
        'BQD Status (BOY)',
        'C&A Score (BOY)',
        'C&A Status (BOY)',
        'Comp Score (BOY)',
        'Comp Status (BOY)',
        'MNF Score (BOY)',
        'MNF Status (BOY)',
        'NIF Score (BOY)',
        'NIF Status (BOY)',
        'NNF Score (BOY)',
        'NNF Status (BOY)',
        'Math Composite Score (MOY)',
        'Math Composite Status (MOY)',
        'AQD Score (MOY)',
        'AQD Status (MOY)',
        'BQD Score (MOY)',
        'BQD Status (MOY)',
        'C&A Score (MOY)',
        'C&A Status (MOY)',
        'Comp Score (MOY)',
        'Comp Status (MOY)',
        'MNF Score (MOY)',
        'MNF Status (MOY)',
        'NIF Score (MOY)',
        'NIF Status (MOY)',
        'NNF Score (MOY)',
        'NNF Status (MOY)',

        # 23-24 Acadience Reading
        '23-24 FSF Score (BOY)',
        '23-24 FSF Status (BOY)',
        '23-24 LNF Score (BOY)',
        '23-24 PSF Score (BOY)',
        '23-24 PSF Status (BOY)',
        '23-24 NWF CLS Score (BOY)',
        '23-24 NWF CLS Status (BOY)',
        '23-24 NWF WWR Score (BOY)',
        '23-24 NWF WWR Status (BOY)',
        '23-24 ORF WC Score (BOY)',
        '23-24 ORF WC Status (BOY)',
        '23-24 ORF Accuracy Score (BOY)',
        '23-24 ORF Accuracy Status (BOY)',
        '23-24 Retell Score (BOY)',
        '23-24 Retell Status (BOY)',
        '23-24 Retell Quality Score (BOY)',
        '23-24 Retell Quality Status (BOY)',
        '23-24 Maze Adjusted Score (BOY)',
        '23-24 Maze Status (BOY)',
        '23-24 Reading Composite Score (BOY)',
        '23-24 Reading Composite Status (BOY)',
        '23-24 Lexile Reading (BOY)',
        '23-24 FSF Score (MOY)',
        '23-24 FSF Status (MOY)',
        '23-24 LNF Score (MOY)',
        '23-24 PSF Score (MOY)',
        '23-24 PSF Status (MOY)',
        '23-24 NWF CLS Score (MOY)',
        '23-24 NWF CLS Status (MOY)',
        '23-24 NWF WWR Score (MOY)',
        '23-24 NWF WWR Status (MOY)',
        '23-24 ORF WC Score (MOY)',
        '23-24 ORF WC Status (MOY)',
        '23-24 ORF Accuracy Score (MOY)',
        '23-24 ORF Accuracy Status (MOY)',
        '23-24 Retell Score (MOY)',
        '23-24 Retell Status (MOY)',
        '23-24 Retell Quality Score (MOY)',
        '23-24 Retell Quality Status (MOY)',
        '23-24 Maze Adjusted Score (MOY)',
        '23-24 Maze Status (MOY)',
        '23-24 Reading Composite Score (MOY)',
        '23-24 Reading Composite Status (MOY)',
        '23-24 Reading Composite Pathway (MOY)',
        '23-24 Lexile Reading (MOY)',
        '23-24 LNF Score (EOY)',
        '23-24 PSF Score (EOY)',
        '23-24 PSF Status (EOY)',
        '23-24 NWF CLS Score (EOY)',
        '23-24 NWF CLS Status (EOY)',
        '23-24 NWF WWR Score (EOY)',
        '23-24 NWF WWR Status (EOY)',
        '23-24 ORF WC Score (EOY)',
        '23-24 ORF WC Status (EOY)',
        '23-24 ORF Accuracy Score (EOY)',
        '23-24 ORF Accuracy Status (EOY)',
        '23-24 Retell Score (EOY)',
        '23-24 Retell Status (EOY)',
        '23-24 Retell Quality Score (EOY)',
        '23-24 Retell Quality Status (EOY)',
        '23-24 Maze Adjusted Score (EOY)',
        '23-24 Maze Status (EOY)',
        '23-24 Reading Composite Score (EOY)',
        '23-24 Reading Composite Status (EOY)',
        '23-24 Reading Composite Pathway (EOY)',
        '23-24 Lexile Reading (EOY)',
        
        # 23-24 Acadience Math
        '23-24 BQD Score (BOY)',
        '23-24 BQD Status (BOY)',
        '23-24 NIF Score (BOY)',
        '23-24 NIF Status (BOY)',
        '23-24 NNF Score (BOY)',
        '23-24 NNF Status (BOY)',
        '23-24 AQD Score (BOY)',
        '23-24 AQD Status (BOY)',
        '23-24 MNF Score (BOY)',
        '23-24 MNF Status (BOY)',
        '23-24 Comp Score (BOY)',
        '23-24 Comp Status (BOY)',
        '23-24 C&A Score (BOY)',
        '23-24 C&A Status (BOY)',
        '23-24 Math Composite Score (BOY)',
        '23-24 Math Composite Status (BOY)',
        '23-24 BQD Score (MOY)',
        '23-24 BQD Status (MOY)',
        '23-24 NIF Score (MOY)',
        '23-24 NIF Status (MOY)',
        '23-24 NNF Score (MOY)',
        '23-24 NNF Status (MOY)',
        '23-24 AQD Score (MOY)',
        '23-24 AQD Status (MOY)',
        '23-24 MNF Score (MOY)',
        '23-24 MNF Status (MOY)',
        '23-24 Comp Score (MOY)',
        '23-24 Comp Status (MOY)',
        '23-24 C&A Score (MOY)',
        '23-24 C&A Status (MOY)',
        '23-24 Math Composite Score (MOY)',
        '23-24 Math Composite Status (MOY)',
        '23-24 Math Composite Pathway (MOY)',
        '23-24 BQD Score (EOY)',
        '23-24 BQD Status (EOY)',
        '23-24 NIF Score (EOY)',
        '23-24 NIF Status (EOY)',
        '23-24 NNF Score (EOY)',
        '23-24 NNF Status (EOY)',
        '23-24 AQD Score (EOY)',
        '23-24 AQD Status (EOY)',
        '23-24 MNF Score (EOY)',
        '23-24 MNF Status (EOY)',
        '23-24 Comp Score (EOY)',
        '23-24 Comp Status (EOY)',
        '23-24 C&A Score (EOY)',
        '23-24 C&A Status (EOY)',
        '23-24 Math Composite Score (EOY)',
        '23-24 Math Composite Status (EOY)',
        '23-24 Math Composite Pathway (EOY)',

        # Rise
        '23-24 ELA Scale Score', 
        '23-24 ELA Performance', 
        '23-24 Reading Informational Text Performance', 
        '23-24 Language Performance', 
        '23-24 Reading Literature Performance', 
        '23-24 Listening Comprehension Performance',
        '23-24 Math Scale Score',
        '23-24 Math Performance', 
        '23-24 Measurement and Data and Geometry Performance', 
        '23-24 Number and Operations in Base Ten Performance', 
        '23-24 Operations and Algebraic Thinking Performance', 
        '23-24 Number and Operations - Fractions Performance',
        # '23-24 Wave Patterns Performance', 
        # '23-24 Organisms Functioning in Their Environment Performance', 
        '23-24 Cycling of Matter in Ecosystems Performance', 
        # '23-24 Observable Patterns in the Sky Performance', 
        "23-24 Characteristics and Interactions of Earth's Systems Performance", 
        '23-24 Science Performance', 
        '23-24 Properties and Changes of Matter Performance', 
        '23-24 Science Scale Score', 
        # '23-24 Energy Transfer Performance',
        '23-24 Opinion: Conventions of Standard English', 
        # '23-24 Writing Score', 
        '23-24 Opinion: Purpose, Focus, and Organization', 
        '23-24 Opinion: Evidence and Elaboration', 
        '23-24 Informative: Evidence and Elaboration', 
        '23-24 Informative: Purpose, Focus, and Organization', 
        '23-24 Informative: Conventions of Standard English'
    ]

    df = pd.DataFrame(list(students.find(query)))

    df = df.loc[:, cols]
    df.fillna('')

    # Authenticate with gspread
    gc = gspread.service_account('creds/service_account.json')

    # Open Google Sheet
    mzc_worksheet = gc.open('MZC Holysheet')
    mzc_sheet = mzc_worksheet.worksheet('mzc')

    return mzc_sheet.update([df.columns.values.tolist()] + df.fillna('').values.tolist())

